--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dam/wallpapers/green-girl.jpg"

-- Special
background="#12100d"
foreground="#e7e4e2"
cursor="#e7e4e2"

-- Colors
color0="#12100d"
color1="#75A98D"
color2="#ADA0A0"
color3="#CBB19E"
color4="#86D69B"
color5="#91E1A2"
color6="#E2D2A2"
color7="#e7e4e2"
color8="#a19f9e"
color9="#75A98D"
color10="#ADA0A0"
color11="#CBB19E"
color12="#86D69B"
color13="#91E1A2"
color14="#E2D2A2"
color15="#e7e4e2"
