# Shell variables
# Generated by 'wal'
wallpaper='/home/dam/wallpapers/green-girl.jpg'

# Special
background='#12100d'
foreground='#e7e4e2'
cursor='#e7e4e2'

# Colors
color0='#12100d'
color1='#75A98D'
color2='#ADA0A0'
color3='#CBB19E'
color4='#86D69B'
color5='#91E1A2'
color6='#E2D2A2'
color7='#e7e4e2'
color8='#a19f9e'
color9='#75A98D'
color10='#ADA0A0'
color11='#CBB19E'
color12='#86D69B'
color13='#91E1A2'
color14='#E2D2A2'
color15='#e7e4e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
